version: '3.8'

services:
  site:
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/site
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - GUNICORN_WORKERS=1
      - GUNICORN_THREADS=5
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_DESTINATION=${MAIL_DESTINATION}
    networks:
      - site_network

networks:
  site_network:
